name: Static analysis

on:
  push:
    branches:
  pull_request:

permissions:
  contents: read

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          extensions: mbstring
          tools: composer

      - name: Download dependencies
        run: composer update --no-interaction --no-progress

      - name: Download PHP CS Fixer
        run: composer bin php-cs-fixer update --no-interaction --no-progress

      - name: Execute PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --diff --dry-run
